export * from './ui/historial/activo/activo.component';
export * from './ui/historial/aprobado/aprobado.component';
export * from './ui/historial/atrasado/atrasado.component';
export * from './ui/historial/base/historial-base';
export * from './ui/historial/cancelado/cancelado.component';
export * from './ui/historial/finalizado/finalizado.component';
export * from './ui/historial/historial.component';
export * from './ui/historial/pendiente/pendiente.component';
export * from './ui/historial/rechazado/rechazado.component';
